const KEY='farmstory-records-v1', PHOTO_KEY='farmstory-photos-v1', REGION_KEY='farmstory-weather-region-v1';
const tabs={home:'오늘',sale:'판매',nutrition:'영양제',spray:'방제',labor:'근로자'};
let tab='home', records=read(KEY), photos=read(PHOTO_KEY);
const today=()=>new Date().toISOString().slice(0,10); const won=n=>new Intl.NumberFormat('ko-KR').format(Number(n||0))+'원';
function read(k){try{return JSON.parse(localStorage.getItem(k))||[]}catch{return[]}} function save(){localStorage.setItem(KEY,JSON.stringify(records));localStorage.setItem(PHOTO_KEY,JSON.stringify(photos))}
function esc(v=''){const d=document.createElement('div');d.textContent=v;return d.innerHTML} function label(k){return tabs[k]||k}
function getRegion(){try{return JSON.parse(localStorage.getItem(REGION_KEY))||{name:'기본 지역',lat:36.30,lon:127.14}}catch{return{name:'기본 지역',lat:36.30,lon:127.14}}}
function prettyDate(){return new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'long'}).format(new Date())}
function homeView(){const todoCount=records.filter(r=>r.kind==='task'&&!r.done).length;return `<section class="home-hero"><div class="hero-copy"><span class="hero-date">${prettyDate()}</span><h1>오늘도 농장의 하루를<br>차곡차곡 기록해 보세요</h1><p>해야 할 일과 농장 기록을 한곳에서 간편하게 관리할 수 있어요.</p><button onclick="openRecord('task')">＋ 오늘 할 일 추가</button></div><div class="hero-count"><span>남은 할 일</span><strong>${todoCount}</strong><small>${todoCount?'하나씩 완료해 보세요':'오늘 일정이 여유로워요'}</small></div></section><section class="quick-section"><div class="quick-heading"><div><span>빠른 기록</span><h2>무엇을 기록할까요?</h2></div><small>자주 쓰는 메뉴를 바로 열 수 있어요</small></div><div class="quick-grid"><button onclick="openRecord('sale')"><span class="quick-icon sale-icon">🧺</span><b>판매</b><small>판매·입금 기록</small></button><button onclick="openRecord('nutrition')"><span class="quick-icon nutrition-icon">🌱</span><b>영양제</b><small>투입 내용 기록</small></button><button onclick="openRecord('spray')"><span class="quick-icon spray-icon">💧</span><b>방제</b><small>약제·예정일 기록</small></button><button onclick="openRecord('labor')"><span class="quick-icon labor-icon">👩‍🌾</span><b>근로</b><small>근무시간 기록</small></button></div></section><div class="section-title"><div><h1>생육 사진</h1><p>작물의 변화를 사진으로 남겨 보세요</p></div><button onclick="openPhoto()">사진 올리기</button></div><div class="photos">${photoView()}</div><div class="section-title"><div><h1>오늘 할 일</h1><p>일정과 방제 예정일을 확인하세요</p></div><button onclick="openRecord('task')">+ 할 일</button></div>`}
function manageView(labor,visible){return `<div class="section-title"><div><h1>${label(tab)} 관리</h1><p>${tab==='sale'?'판매와 입금 기록':tab==='nutrition'?'구역별 영양제 기록':tab==='spray'?'방제와 예정일 기록':'근무시간 기록'}</p></div><button onclick="openRecord('${tab}')">+ 추가</button></div>${tab==='labor'?`<div class="wage"><span>이번 달 총 근무 ${labor}시간</span><b>예상 급여 ${won(labor*10320)}</b><small>시급 10,320원 기준의 참고 금액입니다.</small></div>`:''}<div class="list">${listView(visible)}</div>`}
function render(){const month=today().slice(0,7),labor=records.filter(r=>r.kind==='labor'&&r.date.startsWith(month)&&r.area==='근무').reduce((s,r)=>s+Number(r.hours||0),0),visible=tab==='home'?records.filter(r=>(r.kind==='task'&&(!r.done||r.date===today()))||(r.kind==='spray'&&r.nextDate===today())):records.filter(r=>r.kind===tab),page=tab==='home'?homeView():manageView(labor,visible);document.querySelector('#app').innerHTML=`<header><div class="brand"><span class="logo">🌿</span><div><b>팜스토리</b><small>농장 통합 관리</small></div></div><button class="add" onclick="openRecord('${tab==='home'?'task':tab}')">+ 기록</button></header><div class="weather"><span class="weather-icon">☀️</span><div><small><span id="weather-region">${esc(getRegion().name)}</span> 오늘의 날씨</small><b id="weather">날씨 확인 중</b></div><button class="weather-setting" onclick="openRegion()">지역 설정</button></div><nav>${Object.entries(tabs).map(([k,n])=>`<button class="${tab===k?'on':''}" onclick="switchTab('${k}')">${n}</button>`).join('')}</nav><section class="wrap">${page}</section>`;weather()}
function photoView(){return photos.length?photos.slice(0,4).map(p=>`<figure><img src="${p.url}" alt="${esc(p.date)} ${esc(p.crop)} 생육 사진"><figcaption><b>${esc(p.crop)}</b><span>${esc(p.date)}</span>${p.memo?`<small>${esc(p.memo)}</small>`:''}</figcaption></figure>`).join(''):`<div class="empty photo-empty"><b>아직 생육 사진이 없습니다</b><button onclick="openPhoto()">첫 사진 올리기</button></div>`}
function listView(list){if(!list.length)return `<div class="empty"><b>아직 기록이 없습니다</b><button onclick="openRecord('${tab==='home'?'task':tab}')">첫 기록 남기기</button></div>`;return list.map(r=>`<article class="${r.done?'done':''}">${r.kind==='task'?`<button class="check" onclick="toggleDone(${r.id})">${r.done?'✓':''}</button>`:''}<div class="grow"><div class="row"><em>${label(r.kind)}</em><b>${esc(r.title)}</b></div><p>${[r.date,r.area,r.worker,r.details].filter(Boolean).map(esc).join(' · ')}</p>${r.kind==='sale'?`<p><b>오전 ${r.amQty||0}박스 + 오후 ${r.pmQty||0}박스</b> · ${won(r.amount)} · <button class="paid" onclick="togglePaid(${r.id})">${r.paid?'입금 완료':'입금 전 → 완료 처리'}</button></p>`:''}${r.kind==='labor'?`<p><b>${r.hours||0}시간</b></p>`:''}${r.nextDate?`<p class="alert">다음 방제일 ${esc(r.nextDate)}</p>`:''}<small>작성자 농장 관리자</small></div><button class="delete" onclick="removeRecord(${r.id})" aria-label="삭제">✕</button></article>`).join('')}
function switchTab(k){tab=k;render()} function weather(){const region=getRegion();fetch(`https://api.open-meteo.com/v1/forecast?latitude=${region.lat}&longitude=${region.lon}&current=temperature_2m,weather_code&timezone=Asia%2FSeoul`).then(r=>r.json()).then(d=>{const x=document.querySelector('#weather');if(x)x.textContent=`현재 ${Math.round(d.current.temperature_2m)}℃`;}).catch(()=>{const x=document.querySelector('#weather');if(x)x.textContent='날씨 정보를 불러오지 못했습니다.'})}
function closeModal(){document.querySelector('.shade')?.remove()} function field(n,html){return `<label class="field"><span>${n}</span>${html}</label>`}
function openRegion(){const region=getRegion();document.body.insertAdjacentHTML('beforeend',`<div class="shade"><form class="modal" onsubmit="submitRegion(event)"><div class="modal-head"><h2>날씨 지역 설정</h2><button type="button" onclick="closeModal()">✕</button></div>${field('지역 이름',`<input name="region" value="${esc(region.name==='기본 지역'?'':region.name)}" placeholder="예: 논산, 서울, 제주시" required>`)}<p id="region-message" class="region-message">시·군·구 이름을 입력해 주세요.</p><button class="save">이 지역으로 설정</button></form></div>`)}
async function findRegion(name){const aliases={서울:'서울특별시',부산:'부산광역시',대구:'대구광역시',인천:'인천광역시',광주:'광주광역시',대전:'대전광역시',울산:'울산광역시',세종:'세종특별자치시',제주:'제주시'},candidates=[aliases[name],name,...(/(시|군|구)$/.test(name)?[]:[name+'시',name+'군',name+'구'])].filter((v,i,a)=>v&&a.indexOf(v)===i);for(const candidate of candidates){const response=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(candidate)}&count=1&language=ko&format=json&countryCode=KR`);if(!response.ok)throw new Error('검색 실패');const data=await response.json();if(data.results?.[0])return data.results[0]}return null}
async function submitRegion(e){e.preventDefault();const form=e.target,name=form.region.value.trim(),message=form.querySelector('#region-message'),button=form.querySelector('.save');button.disabled=true;message.textContent='지역을 찾는 중입니다.';try{const place=await findRegion(name);if(!place){message.textContent='지역을 찾지 못했습니다. 시·군·구 이름으로 다시 입력해 주세요.';return}const display=[place.name,place.admin1].filter((v,i,a)=>v&&a.indexOf(v)===i).join(' ');localStorage.setItem(REGION_KEY,JSON.stringify({name:display,lat:place.latitude,lon:place.longitude}));closeModal();render()}catch{message.textContent='지역을 불러오지 못했습니다. 인터넷 연결을 확인해 주세요.'}finally{if(button.isConnected)button.disabled=false}}
function openRecord(kind){const extra=kind==='task'?field('할 일','<input name="title" placeholder="예: 포장재 주문" required>')+field('담당자','<input name="worker" placeholder="담당자 (선택)">')+field('반복','<select name="details"><option>반복 없음</option><option>매일</option><option>매주</option><option>매월</option></select>'):kind==='sale'?field('품목','<input name="area" placeholder="예: 딸기">')+field('판매처','<input name="title" placeholder="예: 온라인 판매" required>')+`<div class="two">${field('오전 수량(박스)','<input name="amQty" type="number" min="0">')}${field('오후 수량(박스)','<input name="pmQty" type="number" min="0">')}</div>`+field('하루 정산금액','<input name="amount" type="number" min="0" required>')+field('입금 예정일','<input name="dueDate" type="date">')+field('비고','<textarea name="details"></textarea>'):kind==='nutrition'||kind==='spray'?field('구역','<input name="area" placeholder="예: 하우스 1동">')+field(kind==='nutrition'?'영양제 기록':'약제·병해충 기록','<textarea name="details" required></textarea>')+(kind==='spray'?field('다음 방제일','<input name="nextDate" type="date">'):''):`${field('근로자','<input name="worker" placeholder="이름 또는 별칭" required>')}${field('상태','<select name="area"><option>근무</option><option>결근</option><option>휴무</option></select>')}${field('근무시간','<input name="hours" type="number" step="0.5" min="0">')}${field('작업 내용','<textarea name="details" required></textarea>')}`;const title=kind==='labor'?'근무 기록':kind==='nutrition'?'영양제 투입':kind==='spray'?'방제 작업':'';document.body.insertAdjacentHTML('beforeend',`<div class="shade"><form class="modal" onsubmit="submitRecord(event,'${kind}','${title}')"><div class="modal-head"><h2>${label(kind)} 기록</h2><button type="button" onclick="closeModal()">✕</button></div>${field('날짜',`<input name="date" type="date" value="${today()}" required>`)}${extra}<button class="save">저장하기</button></form></div>`)}
function submitRecord(e,kind,defaultTitle){e.preventDefault();const r=Object.fromEntries(new FormData(e.target));records.unshift({id:Date.now(),kind,date:r.date,title:r.title||defaultTitle||'기록',area:r.area||'',details:r.details||'',amQty:r.amQty||0,pmQty:r.pmQty||0,amount:r.amount||0,paid:0,dueDate:r.dueDate||'',nextDate:r.nextDate||'',hours:r.hours||0,worker:r.worker||'',done:0});save();closeModal();render()}
function openPhoto(){document.body.insertAdjacentHTML('beforeend',`<div class="shade"><form class="modal" onsubmit="submitPhoto(event)"><div class="modal-head"><h2>생육 사진 올리기</h2><button type="button" onclick="closeModal()">✕</button></div>${field('촬영 날짜',`<input name="date" type="date" value="${today()}" required>`)}${field('작물','<input name="crop" placeholder="예: 딸기" required>')}${field('사진','<input name="photo" type="file" accept="image/*" required>')}${field('메모 (선택)','<textarea name="memo"></textarea>')}<button class="save">사진 저장하기</button></form></div>`)}
function submitPhoto(e){e.preventDefault();const f=e.target.photo.files[0];if(f.size>5*1024*1024){alert('사진은 5MB 이하로 올려 주세요.');return}const reader=new FileReader();reader.onload=()=>{const d=new FormData(e.target);photos.unshift({id:Date.now(),date:d.get('date'),crop:d.get('crop'),memo:d.get('memo'),url:reader.result});save();closeModal();render()};reader.readAsDataURL(f)}
function removeRecord(id){if(confirm('이 기록을 삭제할까요?')){records=records.filter(r=>r.id!==id);save();render()}} function toggleDone(id){records=records.map(r=>r.id===id?{...r,done:!r.done}:r);save();render()} function togglePaid(id){records=records.map(r=>r.id===id?{...r,paid:!r.paid}:r);save();render()} render();
